### ISSUE TITLE
Sound Devices aren't properly reordered

### ISSUE THREAD

**Issue by colemickens** [tsowell/linux-samus#1]
I assume that if I reorder the sound devices through alsa-base.conf, that I should PulseAudio should default to the correct audio output device? It seems to default to HDMI, even if I've done this:

```
 ~  cat /etc/modprobe.d/alsa-base.conf 
options snd_soc_rt5677 index=0
options snd_hda_intel index=1
```

I can manually adjust the sink in `pavucontrol` and it works.

**Comment by tsowell** [comment]
I haven't tried PulseAudio on the Pixel, but I'll look into it later this weekend.  In the meantime, is https://wiki.archlinux.org/index.php/PulseAudio/Examples#Set_the_defaulting_output_source helpful?

**Comment by colemickens** [comment]
Yes, following those instructions worked. Thanks.
