### ISSUE TITLE
Graphics corruption with tiling WMs after resume

### ISSUE THREAD

**Issue by antonl1911** [tsowell/linux-samus#11]
When I'm using full-blown DE (Gnome 3), I have absolutely no problems suspending or resuming the Pixel, but when using awesome or i3, the fonts are missing after resume. Only reboot seems to fix this problem.

**Comment by myf** [comment]
i have this strange behavior as well. For some reason, if you launch chromium/chrome at any moment after the resume everything would start to work magically.

**Comment by antonl1911** [comment]
Well, using 4.1 kernel from https://github.com/raphael/linux-4.1-samus works ok.
