### ISSUE TITLE
No Audio Output

### ISSUE THREAD

**Issue by hacksimus** [tsowell/linux-samus#12]
I'm new to GitHub so please excuse any noob-ness.

I am unable to get any audio output.

Background:

The touchscreen on my new (Purchased 07/2015) Chromebook Pixel 2015 worked with the default Arch installation. The touchpad did not work, and there were no audio devies visible except for HDMI (USB-C ports?) as well as no audio output via speakers nor headphones.

Using this package, the touchpad started working. However, I am still unable to get two finger scrolling to work, and there is still a lack of audio.

I have no "/etc/modprobe.d/alsa-base.conf" file to edit. I could create it, but I was under the impression it should already exist by default.

My default audio device is set to HDMI. I have not found a way to change this yet.

Here is a link to a related Reddit thread:

https://www.reddit.com/r/linux4noobs/comments/3f4j13/arch_chromebook_pixel_no_audio_output/

**Comment by maxabillion** [comment]
Fixed.

When I installed the kernel patches originally, I downloaded the master from Github. After Curling the arch 0.2.2 package like the README say, I was able to run the "ALSA_CONFIG_UCM=ucm..." command, which gave me audio output. 

doh
