### ISSUE TITLE
Avoid editing /boot/grub/grub.cfg

### ISSUE THREAD

**Issue by razor-x** [tsowell/linux-samus#5]
In the README you have 

> Edit GRUB configuration
> 
> Edit /boot/grub/grub.cfg and change /boot/vmlinuz-linux to /boot/vmlinuz-linux-samus and /boot/initramfs-linux.img to /boot/initramfs-linux-samus.img.

I didn't find this necessary: `grub-mkconfig -o /boot/grub/grub.cfg` found both linux and linux-samus and added them to the GRUB menu. In fact, linux-samus was set as the default boot option and linux was placed in the Advanced options menu.

Can this be removed the the README, or perhaps replaced by something that does not edit `/boot/grub/grub.cfg` directly?

**Comment by tsowell** [comment]
Good call.  The instructions in the README now use grub-mkconfig.

Thanks!
